### ISSUE TITLE
Cps1,2,3 does not work!

### ISSUE THREAD

**Issue by cbepx-me** [JustEnoughLinuxOS/distribution#13]
**Describe the bug**
Cps1,2,3 does not work!

**cause**
file: "/usr/config/emulationstation/es_systems.cfg"
"......"
"    <name>cps1</name>"
......
      <emulator name="libretro">
......"

"libretro" it should be "retroarch".
[es_systems_fixed.zip](https://github.com/JustEnoughLinuxOS/distribution/files/8236707/es_systems_fixed.zip)

**Comment by SuperBadger77** [comment]
I wondered why it didn't work on mine - thought it was some sort of config error on my behalf.

**Comment by fewtarius** [comment]
This issue will be fixed in the upcoming release.  Thanks for reporting!
