### ISSUE TITLE
Minor corrections to wiki guide for Cloud Backups 

### ISSUE THREAD

**Issue by daifdaifdaif** [JustEnoughLinuxOS/distribution#178]
There's two parts of the cloud backup guide on the wiki which made me stumble during setting it up on my device. I'd suggest these two small additions:

**First one**
In this section:
https://github.com/JustEnoughLinuxOS/distribution/wiki/Using-Cloud-Drives#setting-up-rclone-detailed-example

When naming the new remote site, I'd add a quick note not to use empty spaces in the site name. Rclone does allow that, but it'll make the rsync command fail when used via the provided script.

I'd suggest to just add: "Avoid using spaces in the site name" after "type in a name for the site, then press enter".

.

**Second one**
In this section:
https://github.com/JustEnoughLinuxOS/distribution/wiki/Using-Cloud-Drives#install-and-run-rclone-on-machine-with-a-web-browser-to-authorize-connection-to-cloud-service

Previously in the guide, it's mentioned, that the user should note the rclone version which the headless device uses. In this part, it's not mentioned that the users should download the same version of rclone on the machine with the webbrowser. If the user downloads a different version, depending on the cloud provider, the setup might fail.

I'd suggest to add: "(Download the same version of rclone as your headless device uses, as you've noted above)" after the link to the rclone download server

**Comment by romadu** [comment]
These changes have been added. Thanks for the feedback.

**Comment by fewtarius** [comment]
Thank you for your feedback!  Thanks @romadu!
