### ISSUE TITLE
Per System and/or Per Game Overclock and Fan Profiles

### ISSUE THREAD

**Issue by trowgundam** [JustEnoughLinuxOS/distribution#37]
I'm not sure if possible, but would it be possible to have the ability to pick an Overclock and Fan Curve based on the System and even game. That way for something like Gameboy I could not use any overclock, since it is unnecessary, and a quiet Fan Curve. But then for more demanding systems like PSP or Dreamcast, especially for the harder to run games, put in place an Overclock while also bumping the Fan Speed to match.

**Comment by fewtarius** [comment]
This is something that we have discussed already and is in our plan to implement.  It should be available in the near future.

**Comment by fewtarius** [comment]
Added in c35ea43b592e1a038c9376d67908a6cc2f65ff15 and 079c18a77c9eaf983c982754f88dec332f220dd8.
