### ISSUE TITLE
RG351V retroarch hotkeys assignment

### ISSUE THREAD

**Issue by buggii** [JustEnoughLinuxOS/distribution#39]
**Describe the bug**
RG351V hotkeys assignment are different from the ones described here: https://www.jelos.org/?

**To Reproduce**
The only hotkeys I was able to find are: 
L3 + F to open retroarch menu
L3 + L2 to fast forward (on game boy emulation)
START + SELECT + L2 = Quit retroarch

**Expected behavior**
Key as described in the main page

**Comment by fewtarius** [comment]
Resolved by 60257301c6e6f680a0838dd94b8df03c184820f0.
