### ISSUE TITLE
Laser disk emulator (HYPSEUS) not working

### ISSUE THREAD

**Issue by buggii** [JustEnoughLinuxOS/distribution#40]
**Describe the bug**
When opening a daphne game (with correct hypseus folder structure) this is the error:
/usr/bin/bash: /usr/bin/hypseus.start.sh: No such file or directory

So the compiled image seems to miss a bash script.

The correct folder structure for HYPSEUS is the following:

roms 
 > daphne
     > lair.daphne
         > lair.dat
         > lair.m2v
         > lair.ogg
         > lair.txt
     > roms
         > lair.zip
     > sound
         > ab_alarm1.wav
         > ab_alarm2.wav
         (more files here)
         > sdq-short-success-low.wav

**To Reproduce**
Try to run a laser disk game.

**Comment by fewtarius** [comment]
Corrected in 96f6b0fe28fb830161489b00f68bdf9e5453b35f
